language: python
python:
  - "3.8"
  - "3.9"
install:
  - export PIPENV_PIPFILE=whiteapp/Pipfile
  - export PYPI_REMOTE=https://pypi.org/simple
  - export PIPPENV_IGNORE_VIRTUALENVS=1
  - python -m pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=tests/conftest.py
  - pipenv run flake8 . --count --exit-zero --extend-ignore=W503,W50 --max-complexity=10 --max-line-length=120 --statistics --exclude=tests/conftest.py
  - pipenv run coverage run --source whiteapp/ -m pytest

after_sucess:
  - bash <(curl -s https://codecov.io/bash)
